### ISSUE TITLE
Rainway Won't Open

### ISSUE THREAD

**Issue by TapuFini** [RainwayApp/bug-tracker#182]
Hello!

Just installed Rainway on my PC tonight for the first time and when I run it from the shortcut, it shows the loading screen then turns off straight away. I've tried reinstalling and rebooting but it doesn't help.

Here's what's coming up in the Windows Error Log:

> Application: Rainway.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.IO.FileNotFoundException
   at System.Signature.GetSignature(Void*, Int32, System.RuntimeFieldHandleInternal, System.IRuntimeMethodInfo, System.RuntimeType)
   at System.Reflection.RuntimeMethodInfo.FetchNonReturnParameters()
   at System.Reflection.RuntimeMethodInfo.GetParameters()
   at Newtonsoft.Json.Serialization.DefaultContractResolver.GetCallbackMethodsForType(System.Type, System.Collections.Generic.List`1<Newtonsoft.Json.Serialization.SerializationCallback> ByRef, System.Collections.Generic.List`1<Newtonsoft.Json.Serialization.SerializationCallback> ByRef, System.Collections.Generic.List`1<Newtonsoft.Json.Serialization.SerializationCallback> ByRef, System.Collections.Generic.List`1<Newtonsoft.Json.Serialization.SerializationCallback> ByRef, System.Collections.Generic.List`1<Newtonsoft.Json.Serialization.SerializationErrorCallback> ByRef)
   at Newtonsoft.Json.Serialization.DefaultContractResolver.ResolveCallbackMethods(Newtonsoft.Json.Serialization.JsonContract, System.Type)
   at Newtonsoft.Json.Serialization.DefaultContractResolver.CreateObjectContract(System.Type)
   at System.Collections.Concurrent.ConcurrentDictionary`2[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089],[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].GetOrAdd(System.__Canon, System.Func`2<System.__Canon,System.__Canon>)
   at Newtonsoft.Json.Serialization.DefaultContractResolver.ResolveContract(System.Type)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(System.Object, Newtonsoft.Json.JsonReader, Newtonsoft.Json.Serialization.JsonObjectContract, Newtonsoft.Json.Serialization.JsonProperty, System.String)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(Newtonsoft.Json.JsonReader, System.Type, Newtonsoft.Json.Serialization.JsonContract, Newtonsoft.Json.Serialization.JsonProperty, Newtonsoft.Json.Serialization.JsonContainerContract, Newtonsoft.Json.Serialization.JsonProperty, System.Object)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(Newtonsoft.Json.Serialization.JsonProperty, Newtonsoft.Json.JsonConverter, Newtonsoft.Json.Serialization.JsonContainerContract, Newtonsoft.Json.Serialization.JsonProperty, Newtonsoft.Json.JsonReader, System.Object)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(System.Object, Newtonsoft.Json.JsonReader, Newtonsoft.Json.Serialization.JsonObjectContract, Newtonsoft.Json.Serialization.JsonProperty, System.String)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(Newtonsoft.Json.JsonReader, System.Type, Newtonsoft.Json.Serialization.JsonContract, Newtonsoft.Json.Serialization.JsonProperty, Newtonsoft.Json.Serialization.JsonContainerContract, Newtonsoft.Json.Serialization.JsonProperty, System.Object)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(Newtonsoft.Json.JsonReader, System.Type, Boolean)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(Newtonsoft.Json.JsonReader, System.Type)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(System.String, System.Type, Newtonsoft.Json.JsonSerializerSettings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]](System.String, Newtonsoft.Json.JsonSerializerSettings)
   at Rainway.Core.Settings.RainwayEnvironment.LoadRainwayConfig()
   at Rainway.Core.Settings.RainwayEnvironment.Setup(Rainway.StartupOptions ByRef)
   at Rainway.Program.Main()

**Comment by BetaLeaf** [comment]
@TapuFini Just to make 100% sure, you are running Windows 10 Fall Creators Update correct?

**Comment by TapuFini** [comment]
@BetaLeaf Hello! Yes I am, running version 1709 - OS Build 16299.248 (latest update)

**Comment by TapuFini** [comment]
@healingbrew unfortunately yes. Have uninstalled and reinstalled it a few times and removed installation files/folders before reinstalling it. I've updated it since but still does the same thing. Perhaps I am missing a dependency that wasn't part of the installation?

**Comment by Codeusa** [comment]
- If you have anti-virus, turn it off and reinstall Rainway.
- Ensure your .NET 4.7.1 installation is working by reinstalling it

**Comment by TapuFini** [comment]
@Codeusa Just did this but it didn't work. I have no anti-virus but disabled Windows Defender etc and reinstalled Rainway. Also removed older versions of .NET and tried the reinstall and repair but to no avail. :(

**Comment by TapuFini** [comment]
@BetaLeaf @healingbrew @Codeusa 
Hello everyone, I can only apologise as this seems to be an issue with just my PC perhaps. After running a game for the first time in ages, it was erroring saying it cannot find MSVCP140.dll or VCRUNTIME140.DLL. So I got these files into my system32 folder and it fixed the game and Rainway too! Thank you for your help and sorry that it was purely my computer's issue!

**Comment by BetaLeaf** [comment]
I hope you didn't use one of the DLL download sites.

**Comment by Jessomadic** [comment]
If they did then they might as well just kill there computer

**Comment by TapuFini** [comment]
@BetaLeaf @Jessomadic Copied them from my boyfriend's PC, which worked fine. Thanks.
