### ISSUE TITLE
Can't Launch Games

### ISSUE THREAD

**Issue by khoanguyen96** [RainwayApp/bug-tracker#204]
On client side an error message similarly to: "Unexpected Launcher Error"

Here's a snippet of the Server.log:

```
2018-03-07 13:09:24,444 [69] WARN Rainway.Core.Games.GameManager - Process could not start. FileName (steam://run/637650) Arguments ()
Warden.Core.Exceptions.WardenLaunchException: Process could not start. FileName (steam://run/637650) Arguments ()
   at Warden.Core.Launchers.UriLauncher.LaunchUriAsync(String uri, String path, String arguments, Boolean asUser)
   at Warden.Core.Launchers.UriLauncher.<PrepareUri>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Warden.Core.WardenProcess.<StartUriAsync>d__78.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Rainway.Core.Games.Launchers.SteamLauncher.<Launch>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Rainway.Core.Games.GameManager.<StartGame>d__4.MoveNext()
```

I'm not too sure if maybe Rainway didn't start properly with the right permissions to launch games?

Additionally, I can't seem to restart Rainway now... A quick look at Event Viewer shows this:

`The Rainway Radar service terminated unexpectedly.  It has done this 1 time(s).`

Thanks! If there's any more information you need, don't hesitate to tell me :')

**Comment by Codeusa** [comment]
@healingbrew I've seen Warden do this when it tries to launch as the user without the proper tokens to do so.


@khoanguyen96 have you tried updating to the latest version and fully restarting Rainway?

**Comment by khoanguyen96** [comment]
Yes. I actually recently updated to the latest version. Restarted Rainway multiple times, and even rebooted the PC haha.

**Comment by khoanguyen96** [comment]
Hey, so I had the time to try different things yesterday. I reinstalled Rainway, and then tested it out locally on the same network with my laptop, and it launched the game perfectly fine...

But once it's not on the same network (as I tested it at a nearby Starbucks) it failed to launch the game?

This might not be related though haha.

Additionally, could it be due to RDP messing with anything though? I used RDP to change a few settings before trying out Rainway...

**Comment by healingbrew** [comment]
For some reason using RDP causes issues, we will be investigating this internally in depth next week.

For now, copy and paste this into a `bat` file (call it `StartRainway.bat` or similar) and use it to start Rainway.

```
set MY_SESSION_ID=unknown
for /f "tokens=3-4" %%a in ('query session %username%') do @if "%%b"=="Active" set MY_SESSION_ID=%%a
tscon %MY_SESSION_ID% /dest:console
"C:\Program Files\RainwayInc\Rainway\server\ServiceManager.exe" 0
```

**Comment by healingbrew** [comment]
This should be fixed now.
