### ISSUE TITLE
Server won't start - cmd window flashes then nothing

### ISSUE THREAD

**Issue by tcoombes** [RainwayApp/bug-tracker#9]
The installer runs through fine, but when i go to start the sever app, a cmd box flashes, then disappears. Only error i can help with is if i go to the rainway folder and run ServiceManger.exe I get a windows 'stopped working' box. 
The service starts and seems to be running fine. 
I have re-installed with the new version a couple of times.

**Comment by Codeusa** [comment]
Can you open up "Event Viewer" and and see if there are any "Error" events related to the Service Manager?

It should look similar to this

![](https://i.imgur.com/Kybudbb.png)

Just copy and paste the text of the general field for the service manager error if it exist.

**Comment by Chaaoos** [comment]
Event ID 7030
> The Rainway Radar service is marked as an interactive service.  However, the system is configured to not allow interactive services.  This service may not function properly.

Not sure if there's more logs somewhere. not fixed on 0.1.2

**Comment by tcoombes** [comment]
hi, sorry for the delay, details below;
Log Name:      Application
Source:        .NET Runtime
Date:          20/01/2018 18:39:20
Event ID:      1026
Task Category: None
Level:         Error
Keywords:      Classic
User:          N/A
Computer:      TomPC-Desktop.Domain.local
Description:
Application: ServiceManager.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.IndexOutOfRangeException
   at ServiceManager.Program.Main(System.String[])


Event Xml:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name=".NET Runtime" />
    <EventID Qualifiers="0">1026</EventID>
    <Level>2</Level>
    <Task>0</Task>
    <Keywords>0x80000000000000</Keywords>
    <TimeCreated SystemTime="2018-01-20T18:39:20.720704500Z" />
    <EventRecordID>12133</EventRecordID>
    <Channel>Application</Channel>
    <Computer>TomPC-Desktop.Domain.local</Computer>
    <Security />
  </System>
  <EventData>
    <Data>Application: ServiceManager.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.IndexOutOfRangeException
   at ServiceManager.Program.Main(System.String[])

</Data>
  </EventData>
</Event>

**Comment by tcoombes** [comment]
also;
Log Name:      Application
Source:        Application Error
Date:          20/01/2018 18:39:20
Event ID:      1000
Task Category: (100)
Level:         Error
Keywords:      Classic
User:          N/A
Computer:      TomPC-Desktop.Domain.local
Description:
Faulting application name: ServiceManager.exe, version: 1.0.0.0, time stamp: 0x5a6378fd
Faulting module name: KERNELBASE.dll, version: 10.0.16299.15, time stamp: 0x4736733c
Exception code: 0xe0434352
Fault offset: 0x0000000000013fb8
Faulting process id: 0x51f8
Faulting application start time: 0x01d3921dfc19a6ea
Faulting application path: C:\Program Files\Rainway, Inc\Rainway\server\ServiceManager.exe
Faulting module path: C:\WINDOWS\System32\KERNELBASE.dll
Report Id: b558da4e-8ee2-4f40-99b5-5a703cf291c3
Faulting package full name: 
Faulting package-relative application ID: 
Event Xml:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name="Application Error" />
    <EventID Qualifiers="0">1000</EventID>
    <Level>2</Level>
    <Task>100</Task>
    <Keywords>0x80000000000000</Keywords>
    <TimeCreated SystemTime="2018-01-20T18:39:20.792750800Z" />
    <EventRecordID>12134</EventRecordID>
    <Channel>Application</Channel>
    <Computer>TomPC-Desktop.Domain.local</Computer>
    <Security />
  </System>
  <EventData>
    <Data>ServiceManager.exe</Data>
    <Data>1.0.0.0</Data>
    <Data>5a6378fd</Data>
    <Data>KERNELBASE.dll</Data>
    <Data>10.0.16299.15</Data>
    <Data>4736733c</Data>
    <Data>e0434352</Data>
    <Data>0000000000013fb8</Data>
    <Data>51f8</Data>
    <Data>01d3921dfc19a6ea</Data>
    <Data>C:\Program Files\Rainway, Inc\Rainway\server\ServiceManager.exe</Data>
    <Data>C:\WINDOWS\System32\KERNELBASE.dll</Data>
    <Data>b558da4e-8ee2-4f40-99b5-5a703cf291c3</Data>
    <Data>
    </Data>
    <Data>
    </Data>
  </EventData>
</Event>

**Comment by Codeusa** [comment]
@Chaaoos your issue will be fixed in the next patch 

@tcoombes Go to 

```
C:\Windows\System32\config\systemprofile\AppData\Roaming\RainwayInc
```

Give me your Server.log and Radar.log, both inside the folders named the same.

**Comment by tcoombes** [comment]
[Radar.log](https://github.com/RainwayApp/bug-tracker/files/1649310/Radar.log)

server log is empty

**Comment by tcoombes** [comment]
but even my novice eyes think that thats pretty useless. if it helps, servicemanager.exe crashes on launch, but only if i run it from the program files folder, if i run the shortcut, it just flashes cmd then nothing

**Comment by Codeusa** [comment]
I will be adding more logging in the next update and addressing a few startup issues. I will circle back after to check if your issue is resolved.

**Comment by LoganVanVleet** [comment]
Same error I have running on AWS, updates didn’t fix it

**Comment by tcoombes** [comment]
you must be crazy busy but just an Fyi, this is still a problem on 0.1.4 for me

**Comment by LoganVanVleet** [comment]
Server Log

2018-01-21 04:29:01,339 [1] WARN Rainway.Core.Windows.Hardware.HardwareInfo - Cannot locate displays.
2018-01-21 04:29:01,392 [1] WARN Rainway.Core.Windows.Hardware.HardwareInfo - Found no displays from COM.
2018-01-21 04:34:39,616 [1] WARN Rainway.Core.Windows.Hardware.HardwareInfo - Cannot locate displays.
2018-01-21 04:34:39,664 [1] WARN Rainway.Core.Windows.Hardware.HardwareInfo - Found no displays from COM.
2018-01-21 05:39:29,541 [1] WARN Rainway.Core.Windows.Hardware.HardwareInfo - Cannot locate displays.
2018-01-21 05:39:29,588 [1] WARN Rainway.Core.Windows.Hardware.HardwareInfo - Found no displays from COM.

Radar Log
2018-01-21 05:39:26,120 [8] WARN Radar.Updaters.Daemons.FrontendDaemon - Skipping because frontend is up-to-date
2018-01-21 05:39:26,182 [18] DEBUG Radar.Updaters.Daemons.FrontendDaemon - Checking for update 1/21/2018 5:39:26 AM
2018-01-21 05:39:26,432 [18] WARN Radar.Updaters.Daemons.FrontendDaemon - Skipping because frontend is up-to-date
2018-01-21 05:39:26,479 [8] WARN Radar.Updaters.Daemons.ServerDaemon - Rainway Update Task Installed!
2018-01-21 05:39:26,651 [8] DEBUG Radar.RadarAgent - Rainway started as a service!
2018-01-21 05:49:55,866 [41] DEBUG Radar.RadarAgent - Session change detected: 2
2018-01-21 05:49:56,382 [35] DEBUG Radar.RadarAgent - Session change detected: 2

**Comment by tcoombes** [comment]
ok, so @LoganVanVleet has found out that this is only an issue when starting the server via rdp  we both used chrome remote desktop instead and the server application launched immediately  

maybe rename the bug to cant start via rdp?

**Comment by trilleplay** [comment]
No, i have this problem as well, but i don't have a RDP server riding on my computer.

What version of windows are you guys running, I'm starting to think the problem is I'm running 1703 and not 1709.

Gonna update win, uninstall rainway, and then install it once again.

I'll let you know if this is the issue.

**Comment by rodrigomiguele** [comment]
I'm also having some trouble to start Rainway Server.

```
Aplicativo: Rainway.exe
Versão do Framework: v4.0.30319
Descrição: O processo foi terminado devido a uma exceção sem tratamento.
Informações da Exceção: System.Runtime.InteropServices.COMException
   em System.RuntimeTypeHandle.CreateInstance(System.RuntimeType, Boolean, Boolean, Boolean ByRef, System.RuntimeMethodHandleInternal ByRef, Boolean ByRef)
   em System.RuntimeType.CreateInstanceSlow(Boolean, Boolean, Boolean, System.Threading.StackCrawlMark ByRef)
   em System.Activator.CreateInstance(System.Type, Boolean)
   em System.Activator.CreateInstance(System.Type)
   em Rainway.Core.Windows.Hardware.HardwareInfo.Load()
   em Rainway.Core.Settings.RainwayEnvironment.Setup(Rainway.StartupOptions ByRef)
   em Rainway.Program.Main()
```

**Comment by Codeusa** [comment]
Update to the latest version (0.1.9) to resolve this.

**Comment by Chaaoos** [comment]
Issue still not resolved in latest version (0.1.12)

Managed to keep the console window open long enough to read what it said.

![image](https://user-images.githubusercontent.com/22846042/35241903-51678520-ffb8-11e7-93ba-2b4587f8fed0.png)
```
Unhandled Exception: System.FormatException: Input string was not in a correct format.
  
   at System.Number.StringToNumber(String str, NumberStyles options, NumberBuffer& number, NumberFormatInfo info, Boolean parseDecimal)

   at System.Number.ParseInt32(String s, NumberStyles style, NumberFormatInfo info)

   at ServiceManager.Program.Main(String[] args)
```

**Comment by Codeusa** [comment]
are you running this directly or via the start menu?

**Comment by Chaaoos** [comment]
Via the start menu.

**Comment by bui** [comment]
I'm also having this issue.

Radar:
```2018-01-23 21:35:37,035 [19] WARN Radar.Updaters.Daemons.FrontendDaemon - Skipping because frontend is up-to-date
2018-01-23 21:35:37,081 [21] DEBUG Radar.Updaters.Daemons.FrontendDaemon - Checking for update 1/23/2018 9:35:37 PM
2018-01-23 21:35:37,300 [19] WARN Radar.Updaters.Daemons.ServerDaemon - Rainway Update Task Installed!
2018-01-23 21:35:37,456 [19] DEBUG Radar.RadarAgent - Rainway started as a service!
2018-01-23 21:35:37,597 [22] WARN Radar.Updaters.Daemons.FrontendDaemon - Skipping because frontend is up-to-date
```

Server:
```2018-01-23 21:35:40,394 [1] WARN Rainway.Core.Windows.Hardware.HardwareInfo - Could not locate a GPU with the given friendly name, might not exist.
2018-01-23 21:35:40,425 [1] WARN Rainway.Core.Windows.Hardware.HardwareInfo - Attempting to set next best case.
2018-01-23 21:35:40,425 [1] WARN Rainway.Core.Windows.Hardware.HardwareInfo - Cannot find any gpu, enabling software.
2018-01-23 21:35:40,441 [1] WARN Rainway.Core.Windows.Hardware.HardwareInfo - Setting software encoding.
2018-01-23 21:35:40,441 [1] WARN Rainway.Core.Windows.Hardware.HardwareInfo - Unable to locate audio.. Resetting.
2018-01-23 21:35:40,441 [1] WARN Rainway.Core.Windows.Hardware.HardwareInfo - Could not locate a GPU with the given friendly name, might not exist.
2018-01-23 21:35:40,441 [1] WARN Rainway.Core.Windows.Hardware.HardwareInfo - Attempting to set next best case.
2018-01-23 21:35:40,441 [1] WARN Rainway.Core.Windows.Hardware.HardwareInfo - Cannot find any gpu, enabling software.
2018-01-23 21:35:40,441 [1] WARN Rainway.Core.Windows.Hardware.HardwareInfo - Setting software encoding.
2018-01-23 21:35:40,441 [1] WARN Rainway.Core.Windows.Hardware.HardwareInfo - Unable to locate audio.. Resetting.
2018-01-23 21:35:40,441 [1] WARN Rainway.Core.Windows.Hardware.HardwareInfo - Could not locate a GPU with the given friendly name, might not exist.
2018-01-23 21:35:40,441 [1] WARN Rainway.Core.Windows.Hardware.HardwareInfo - Attempting to set next best case.
2018-01-23 21:35:40,441 [1] WARN Rainway.Core.Windows.Hardware.HardwareInfo - Cannot find any gpu, enabling software.
2018-01-23 21:35:40,441 [1] WARN Rainway.Core.Windows.Hardware.HardwareInfo - Setting software encoding.
2018-01-23 21:35:40,441 [1] WARN Rainway.Core.Windows.Hardware.HardwareInfo - Setting software encoding.
```

The GPU is a Tesla M60, if it matters.

**Comment by bui** [comment]
Just tested @tcoombes's theory and it's true -- Rainway launches fine when using Chrome Remote Desktop. Wasn't working with RDP.

**Comment by RSickenberg** [comment]
I have this 👍 

`Configuration Result:
[Success] Name RainwayRadar
[Success] DisplayName Rainway Radar
[Success] Description A radar service to ensure Rainway is running.
[Success] ServiceName RainwayRadar
Topshelf v4.0.0.0, .NET Framework v4.0.30319.42000
The RainwayRadar service is now running, press Control+C to exit.
2018-01-28 12:40:52,708 WARN Radar.Updaters.Daemons.FrontendDaemon - Frontend validated.
2018-01-28 12:40:52,723 DEBUG Radar.Updaters.Daemons.FrontendDaemon - Checking for update 28.01.2018 12:40:52
2018-01-28 12:40:53,381 WARN Radar.Updaters.Daemons.FrontendDaemon - Skipping because frontend is up-to-date
Topshelf.Hosts.ConsoleRunHost Critical: 0 : The service threw an unhandled exception, System.UnauthorizedAccessException: Accès refusé. (Exception de HRESULT : 0x80070005 (E_ACCESSDENIED))
   à Microsoft.Win32.TaskScheduler.V2Interop.ITaskFolder.RegisterTaskDefinition(String Path, ITaskDefinition pDefinition, Int32 flags, Object UserId, Object password, TaskLogonType LogonType, Object sddl)
   à Microsoft.Win32.TaskScheduler.TaskFolder.RegisterTaskDefinition(String path, TaskDefinition definition, TaskCreation createType, String userId, String password, TaskLogonType logonType, String sddl)
   à Microsoft.Win32.TaskScheduler.TaskFolder.RegisterTaskDefinition(String path, TaskDefinition definition)
   à Radar.Updaters.Daemons.ServerDaemon.Setup()
   à Radar.RadarAgent.<StartUp>d__11.MoveNext()
--- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
   à System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   à System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   à System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   à System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   à System.Threading.ThreadPoolWorkQueue.Dispatch()
Stopping the RainwayRadar service
The RainwayRadar service has stopped.
`

**Comment by shirbr510** [comment]
on my PC (win10) I'm facing this error:

Faulting application name: Radar.exe, version: 1.0.2.0, time stamp: 0x5a6d6a6a
Faulting module name: unknown, version: 0.0.0.0, time stamp: 0x00000000
Exception code: 0x80131623
Fault offset: 0x00007ff857a04d3c
Faulting process id: 0x3228
Faulting application start time: 0x01d39877a0915c97
Faulting application path: C:\Program Files\RainwayInc\Rainway\server\Radar.exe
Faulting module path: unknown
Report Id: bfba3f02-d3c6-4c3b-8370-2dbe4e23fa53
Faulting package full name: 
Faulting package-relative application ID:

**Comment by healingbrew** [comment]
RDP support should be fixed now.
